my_blog/urls.py
from django.contrib import admin
from django.urls import path, include

import notifications.urls

from article.views import article_list
# 参数article分配了app的访问路径
# 'include' 将路径分发给下一步处理
# 'namespace' 可以保证反查到唯一的url，即使不同的app使用了相同的url
#
# 存放映射关系的列表
urlpatterns = [
    path(
        'admin/',
        admin.site.urls
    ),
    # 配置app的url
    path(
        'article/',
        include('article.urls', namespace='article')
    ),
    # 用户管理
    path(
        'userprofile/',
        include('userprofile.urls', namespace='userprofile')
    ),
    # 密码重置-第三方库
    path(
        'password-reset/',
        include('password_reset.urls')
    ),
    # 评论
    path(
        'comment/',
        include('comment.urls', namespace='comment')
    ),
    # 通知
    path(
        'inbox/notifications/',
        include(notifications.urls,namespace='notifications')
    ),
    # notice
    path(
        'notice/',
        include('notice.urls', namespace='notice')
    ),
    # django-allauth
    path(
        'accounts/',
        include('allauth.urls')
    ),
    # home
    path(
        '',
        article_list,
        name='home'
    ),
]
# 通过path将根路径为article的访问都分发给article这个app去处理
# 但app通常有多个页面地址，因为还需要app自己也有一个路由分发，就是指article.urls

# 上传图片
# 新引入的模块
from django.conf import settings
from django.conf.urls.static import static

# 添加这行
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    # 通知列表
    # path()的第二个参数只能接收函数，
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    # 更新通知状态
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path(
        'login/',
        views.user_login,
        name='login'
    ),
    # 用户退出
    path(
        'logout/',
        views.user_logout,
        name='logout'
    ),
    # 用户注册
    path(
        'register/',
        views.user_register,
        name='register'
    ),
    # 用户删除
    path(
        'delete/<int:id>/',
        views.user_delete,
        name='delete'
    ),
    # 用户信息
    path(
        'edit/<int:id>/',
        views.profile_edit,
        name='edit'
    ),

]

userprofile/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    phone = models.CharField(max_length=20, blank=True)
    # upload_to指定了图片上传的位置，
    # 即/media/avatar/%Y%m%d/。%Y%m%d是日期格式化的写法，
    # 最终格式化为系统时间。
    # ImageField字段不会存储图片本身，而仅仅保存图片的地址。
    avatar = models.ImageField(upload_to='avatar/%Y%m%d/', blank=True)
    bio = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return 'user {}'.format(self.user.username)

# User和Profile的同步创建，但是也产生了一个BUG：
# 在后台中创建User时如果填写了Profile任何内容，
# 则系统报错且保存不成功；其他情况下均正常。
# **BUG产生原因：**在后台中创建并保存User时调用了信号接收函数，
# 创建了Profile表；
# 但如果此时管理员填写了内联的Profile表，会导致此表也会被创建并保存。
# 最终结果就是同时创建了两个具有相同User的Profile表，违背了”一对一“外键的原则。

# from django.db import models
# from django.contrib.auth.models import User
# # 引入内置信号
# from django.db.models.signals import post_save
# # 引入信号接收器的装饰器
# from django.dispatch import receiver


# # 用户扩展信息
# class Profile(models.Model):
#     # 与 User 模型构成一对一的关系
#     # 每个Profile模型对应唯一的一个User模型，
#     # 形成了对User的外接扩展，
#     # 因此你可以在Profile添加任何想要的字段。
#     # 这种方法的好处是不需要对User进行任何改动，
#     # 从而拥有完全自定义的数据表。
#     user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
#     # 电话号码字段
#     phone = models.CharField(max_length=20, blank=True)
#     # 头像
#     avatar = models.ImageField(upload_to='avatar/%Y%m%d/', blank=True)
#     # 个人简介
#     bio = models.TextField(max_length=500, blank=True)
#
#     def __str__(self):
#         return 'user {}'.format(self.user.username)
#
#
# # 信号接收函数，每当新建 User 实例时自动调用
# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(user=instance)
#
#
# # Django包含一个“信号调度程序”，
# # 它可以在框架中的某些位置发生操作时，通知其他应用程序。
# # 简而言之，信号允许某些发送者通知一组接收器已经发生了某个动作。
# # 当许多代码可能对同一事件感兴趣时，信号就特别有用。
# # 这里引入的post_save就是一个内置信号，它可以在模型调用save()方法后发出信号。
# # 有了信号之后还需要定义接收器，
# # 告诉Django应该把信号发给谁。
# # 装饰器receiver就起到接收器的作用。
# # 每当User有更新时，
# # 就发送一个信号启动post_save相关的函数。
# # 通过信号的传递，实现了每当User创建/更新时，Profile也会自动的创建/更新。
# # 信号接收函数，每当更新 User 实例时自动调用
# @receiver(post_save, sender=User)
# def save_user_profile(sender, instance, **kwargs):
#     instance.profile.save()

userprofile/forms.py
# 引入表单类
from django import forms
# 引入 User 模型
from django.contrib.auth.models import User


# 在前面发表文章的模块中，表单类继承了forms.ModelForm，
# 这个父类适合于需要直接与数据库交互的功能，
# 比如新建、更新数据库的字段等。
# 如果表单将用于直接添加或编辑Django模型，
# 则可以使用 ModelForm来避免重复书写字段描述。
#
# 而forms.Form则需要手动配置每个字段，
# 它适用于不与数据库进行直接交互的功能。
# 用户登录不需要对数据库进行任何改动，
# 因此直接继承forms.Form就可以了。

# 登录表单，继承了 forms.Form 类
class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()


# 验证密码一致性方法不能写def clean_password()，
# 因为如果你不定义def clean_password2()方法，
# 会导致password2中的数据被Django判定为无效数据从而清洗掉，
# 从而password2属性不存在。最终导致两次密码输入始终会不一致，
# 并且很难判断出错误原因。

# 从POST中取值用的data.get('password')是一种稳妥的写法，
# 即使用户没有输入密码也不会导致程序错误而跳出。
# 前面提取POST数据用data['password']，
# 这种取值方式如果data中不包含password，Django会报错。
# 另一种防止用户不输入密码就提交的方式是在表单中插入 required 属性，
# 注册用户表单
class UserRegisterForm(forms.ModelForm):
    # 复写 User 的密码
    password = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = User
        fields = ('username', 'email')

    # 对两次输入的密码是否一致进行检查
    # 自动调用
    def clean_password2(self):
        data = self.cleaned_data
        if data.get('password') == data.get('password2'):
            return data.get('password')
        else:
            raise forms.ValidationError("密码输入不一致,请重试。")


# 引入 Profile 模型
from .models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('phone', 'avatar', 'bio')

userprofile/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from .forms import UserLoginForm


# Create your views here.

def user_login(request):
    if request.method == 'POST':
        user_login_form = UserLoginForm(data=request.POST)
        # Form对象的主要任务就是验证数据。调用is_valid()
        # 方法验证并返回指定数据是否有效的布尔值。
        if user_login_form.is_valid():
            # .cleaned_data 清洗出合法数据
            # 将其标准化为一致的格式，
            # 这个特性使得它允许以各种方式输入特定字段的数据，
            # 并且始终产生一致的输出。
            data = user_login_form.cleaned_data
            # 检验账号、密码是否正确匹配数据库中的某个用户
            # 如果均匹配则返回这个 user 对象
            # authenticate()方法验证用户名称和密码是否匹配，
            # 如果是，则将这个用户数据返回。
            user = authenticate(username=data['username'], password=data['password'])
            if user:
                # 将用户数据保存在 session 中，即实现了登录动作

                # Session在网络应用中，称为“会话控制”，
                # 它存储特定用户会话所需的属性及配置信息。
                # 当用户在 Web 页之间跳转时，
                # 存储在 Session 对象中的变量将不会丢失，
                # 而是在整个用户会话中一直存在下去。
                # Session 最常见的用法就是存储用户的登录数据。
                login(request, user)
                return redirect("article:article_list")
            else:
                return HttpResponse("账号或密码输入有误。请重新输入~")
        else:
            return HttpResponse("账号或密码输入不合法")
    elif request.method == 'GET':
        user_login_form = UserLoginForm()
        context = {'form': user_login_form}
        return render(request, 'userprofile/login.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")


# 引入logout模块
from django.contrib.auth import authenticate, login, logout


# 用户退出
def user_logout(request):
    logout(request)
    return redirect("article:article_list")


# 引入 UserRegisterForm 表单类
from .forms import UserLoginForm, UserRegisterForm


# 用户注册
def user_register(request):
    if request.method == 'POST':
        user_register_form = UserRegisterForm(data=request.POST)
        if user_register_form.is_valid():
            new_user = user_register_form.save(commit=False)
            # 设置密码
            new_user.set_password(user_register_form.cleaned_data['password'])
            new_user.save()
            # 保存好数据后立即登录并返回博客列表页面
            login(request, new_user)
            return redirect("article:article_list")
        else:
            return HttpResponse("注册表单输入有误。请重新输入~")
    elif request.method == 'GET':
        user_register_form = UserRegisterForm()
        context = {'form': user_register_form}
        return render(request, 'userprofile/register.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")


from django.contrib.auth.models import User
# 引入验证登录的装饰器
from django.contrib.auth.decorators import login_required


# @login_required要求调用user_delete()函数时，
# 用户必须登录；如果未登录则不执行函数，
# 将页面重定向到/userprofile/login/地址去

# 装饰器确认用户已经登录后，允许调用user_delete()；
# 然后需要删除的用户id通过请求传递到视图中，
# 由if语句确认是否与登录的用户一致，
# 成功后则退出登录并删除用户数据，返回博客列表页面
@login_required(login_url='/userprofile/login/')
def user_delete(request, id):
    if request.method == 'POST':
        user = User.objects.get(id=id)
        # 验证登录用户、待删除用户是否相同
        if request.user == user:
            # 退出登录，删除数据并返回博客列表
            logout(request)
            user.delete()
            return redirect("article:article_list")
        else:
            return HttpResponse("你没有删除操作的权限。")
    else:
        return HttpResponse("仅接受post请求。")



from .forms import ProfileForm
from .models import Profile


# 编辑用户信息
@login_required(login_url='/userprofile/login/')
def profile_edit(request, id):
    user = User.objects.get(id=id)
    # user_id 是 OneToOneField 自动生成的字段
    # 用来表征两个数据表的关联。你可以在SQLiteStudio中查看它。
    # 旧代码
    # profile = Profile.objects.get(user_id=id)
    # 修改后的代码
    if Profile.objects.filter(user_id=id).exists():
        profile = Profile.objects.get(user_id=id)
    else:
        profile = Profile.objects.create(user=user)

    if request.method == 'POST':
        # 验证修改数据者，是否为用户本人
        if request.user != user:
            return HttpResponse("你没有权限修改此用户信息。")

        # 上传的文件保存在 类字典对象 request.FILES 中，通过参数传递给表单类
        profile_form = ProfileForm(request.POST, request.FILES)
        if profile_form.is_valid():
            # 取得清洗后的合法数据
            profile_cd = profile_form.cleaned_data
            profile.phone = profile_cd['phone']
            profile.bio = profile_cd['bio']

            # 如果request.FILES中存在键为avatar的元素，
            # 则将其赋值给profile.avatar（注意保存的是图片地址）；
            # 否则不进行处理。
            if 'avatar' in request.FILES:
                profile.avatar = profile_cd["avatar"]
            profile.save()
            # 带参数的 redirect()
            return redirect("userprofile:edit", id=id)
        else:
            return HttpResponse("注册表单输入有误。请重新输入~")

    elif request.method == 'GET':
        profile_form = ProfileForm()
        context = {'profile_form': profile_form, 'profile': profile, 'user': user}
        return render(request, 'userprofile/edit.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")

templates/userprofile/edit.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 用户信息 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <div class="col-md-4">用户名: {{ user.username }}</div>
            <br>
<!--            模板语法\{\% if ... \%\}判断用户是否上传头像。-->
            {% if profile.avatar %}
                <div class="col-md-4">头像</div>
<!--            <img>标签用于显示图片内容；
                在style属性中规定了图片的最大宽度并带有一点的圆角。-->
                <img src="{{ profile.avatar.url }}"
                     style="max-width: 20%;
                      border-radius: 15%;"
                     class="col-md-4">
            {% else %}
                <h5 class="col-md-4">暂无头像</h5>
            {% endif %}
            <br>
<!--            表单必须设置enctype="multipart/form-data"属性，才能够正确上传图片等文件。-->
                <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}
                    <!-- avatar -->
                    <div class="form-group col-md-4">
                        <label for="avatar">上传头像</label>
<!--                        添加<input type="file" ...>标签用于上传图片。-->
                        <input type="file" class="form-control-file" name="avatar" id="avatar">
                    </div>

                <!-- phone -->
                <div class="form-group col-md-4">
                    <label for="phone">电话</label>
<!--                    行内文本通过value属性设置了初始值，而多行文本则直接设置{{ profile.bio }}-->
                    <input type="text" class="form-control" id="phone" name="phone" value="{{ profile.phone }}">
                </div>
                <!-- bio -->
                <div class="form-group col-md-4">
                    <label for="bio">简介</label>
                    <textarea type="text" class="form-control" id="bio" name="bio" rows="12">{{ profile.bio }}</textarea>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">提交</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/userprofile/login.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 登录 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <h5>还没有账号？</h5>
            <h5>点击<a href='{% url "userprofile:register" %}'>注册账号</a>加入我们吧！</h5>
            <br>
            <form method="post" action=".">
                ...
            </form>
        </div>
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <!-- 账号 -->
                <div class="form-group">
                    <label for="username">账号</label>
                    <input type="text" class="form-control" id="username" name="username">
                </div>
                <!-- 密码 -->
                <div class="form-group">
                    <label for="password">密码</label>
<!--                    type="password"，可以让输入密码的时候显示小圆点，避免有人偷窥-->
                    <input type="password" class="form-control" id="password" name="password">
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">提交</button>
            </form>
            <!-- 新增 -->
            <br>
            <h5>忘记密码了？</h5>
            <h5>点击<a href='{% url "password_reset_recover" %}'>这里</a>重置密码</h5>
        </div>
    </div>
</div>
{% endblock content %}

templates/userprofile/register.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 登录 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <!-- 账号 -->
                <div class="form-group col-md-4">
                    <label for="username">昵称</label>
<!--                如果用户不填写带有required属性的字段，表单就不能提交，并提示用户填写。-->
                    <input type="text" class="form-control" id="username" name="username" required>
                </div>
                <!-- 邮箱 -->
                <div class="form-group col-md-4">
                    <label for="email">Email</label>
                    <input type="text" class="form-control" id="email" name="email" required>
                </div>
                <!-- 密码 -->
                <div class="form-group col-md-4">
                    <label for="password">设置密码</label>
                    <input type="password" class="form-control" id="password" name="password" required>
                </div>
                <!-- 确认密码 -->
                <div class="form-group col-md-4">
                    <label for="password2">确认密码</label>
                    <input type="password" class="form-control" id="password2" name="password2" required>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">提交</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}