article/urls.py
# 引入path
from django.urls import path
# 引入views.py
from . import views

# 正在部署的应用的名称
#    可以不用配置，只要my_blog中配置了namespace 就不用
app_name = 'article'
# 必须配置app_name，否则会报错

# 根据用户请求的URL选择使用哪个视图
# 当请求article/article-list链接时
# 会调用views.py中的article_list函数，并返回渲染后的对象
# name 用于反查url地址。类似于给url起个名字

# url地址http://127.0.0.1:8000/article/article-list/
# 其中 127.0.0.1是调试服务器的本地地址
# article是项目路由 my_blog\urls.py分发的地址
# article-list是刚配置的article\urls.py应用分发的地址

# 存放映射关系的列表
urlpatterns = [
    # path函数将url映射到视图
    path(
        'article-list/',
        views.article_list,
        name='article_list'
    ),
    # 文章详情
    # <> 定义需要传递的参数
    # 需要传递名为 ID 的整数到视图函数中去
    # 老版本中没有 path 语法的
    path(
        'article-detail/<int:id>/',
        views.article_detail,
        name='article_detail'
    ),
    # 写文章
    path(
        'article-create/',
        views.article_create,
        name='article_create'
    ),
    # 删除文章
    path(
        'article-delete/<int:id>/',
        views.article_delete,
        name='article_delete'
    ),
    # 安全删除文章
    path(
        'article-safe-delete/<int:id>/',
        views.article_safe_delete,
        name='article_safe_delete'
    ),
    # 更新文章
    path(
        'article-update/<int:id>/',
        views.article_update,
        name='article_update'
    ),
    # 点赞 +1
    path(
        'increase-likes/<int:id>/',
        views.IncreaseLikesView.as_view(),
        name='increase_likes'
    ),

    # # 列表类视图
    # path('list-view/', views.ArticleListView.as_view(), name='list_view'),
    # # 详情类视图
    # path('detail-view/<int:pk>/', views.ArticleDetailView.as_view(), name='detail_view'),
    # # 创建类视图
    # path('create-view/', views.ArticleCreateView.as_view(), name='create_view'),

]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include

import notifications.urls

from article.views import article_list
# 参数article分配了app的访问路径
# 'include' 将路径分发给下一步处理
# 'namespace' 可以保证反查到唯一的url，即使不同的app使用了相同的url
#
# 存放映射关系的列表
urlpatterns = [
    path(
        'admin/',
        admin.site.urls
    ),
    # 配置app的url
    path(
        'article/',
        include('article.urls', namespace='article')
    ),
    # 用户管理
    path(
        'userprofile/',
        include('userprofile.urls', namespace='userprofile')
    ),
    # 密码重置-第三方库
    path(
        'password-reset/',
        include('password_reset.urls')
    ),
    # 评论
    path(
        'comment/',
        include('comment.urls', namespace='comment')
    ),
    # 通知
    path(
        'inbox/notifications/',
        include(notifications.urls,namespace='notifications')
    ),
    # notice
    path(
        'notice/',
        include('notice.urls', namespace='notice')
    ),
    # django-allauth
    path(
        'accounts/',
        include('allauth.urls')
    ),
    # home
    path(
        '',
        article_list,
        name='home'
    ),
]
# 通过path将根路径为article的访问都分发给article这个app去处理
# 但app通常有多个页面地址，因为还需要app自己也有一个路由分发，就是指article.urls

# 上传图片
# 新引入的模块
from django.conf import settings
from django.conf.urls.static import static

# 添加这行
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    # 通知列表
    # path()的第二个参数只能接收函数，
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    # 更新通知状态
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path(
        'login/',
        views.user_login,
        name='login'
    ),
    # 用户退出
    path(
        'logout/',
        views.user_logout,
        name='logout'
    ),
    # 用户注册
    path(
        'register/',
        views.user_register,
        name='register'
    ),
    # 用户删除
    path(
        'delete/<int:id>/',
        views.user_delete,
        name='delete'
    ),
    # 用户信息
    path(
        'edit/<int:id>/',
        views.profile_edit,
        name='edit'
    ),

]

templates/back_to_top_func.html
<!-- 参考了 鹦鹉 的代码，在此致谢 -->
<!-- https://ezbox.idv.tw/131/back-to-top-button-without-images -->

<!--，用button标签表示了浮动按钮的容器。-->
<button type="button" id="BackTop" class="toTop-arrow" style="z-index: 100;"></button>

<!--用到了Jquery的语法。页面加载完成后开始监听两个事件：-->
<!--当用户点击浮动按钮时，将页面滚动到顶部-->
<!--当页面滚动时，根据页面距离顶部的距离，决定按钮显示或隐藏-->
<script>
    // 向上滚动的函数
    $(function () {
        $('#BackTop').click(function () {
            $('html,body').animate({scrollTop: 0}, 500);
        });
        $(window).scroll(function () {
            if ($(this).scrollTop() > 300) {
                $('#BackTop').fadeIn(300);
            } else {
                $('#BackTop').stop().fadeOut(300);
            }
        }).scroll();
    });
</script>

<!--定义了按钮的位置、大小、图案等样式。-->
<style>
    /* 按钮边框的大小、位置、样式 */
    .toTop-arrow {
        width: 3.5rem;
        height: 3.5rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 33%;
        opacity: 0.7;
        background: black;
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 1.5rem;
        display: none;
    }

    /* 绘制按钮中的向上箭头 */
    .toTop-arrow::before, .toTop-arrow::after {
        width: 31px;
        height: 7px;
        border-radius: 3px;
        background: orange;
        position: absolute;
        content: "";
    }

    .toTop-arrow::before {
        transform: rotate(-45deg) translate(0, -50%);
        left: 0.4rem;
    }

    .toTop-arrow::after {
        transform: rotate(45deg) translate(0, -50%);
        right: 0.4rem;
    }

    /* 取消点击按钮时的聚焦 */
    .toTop-arrow:focus {
        outline: none;
    }
</style>

templates/base.html
<!DOCTYPE html>
<!--
    载入静态文件
    使用 Django 3 学习的读者改为 {% load static %}
-->
<!--先加上这个，才能使用-->
<!--\{\% static 'path' \%\}引用静态文件-->
{% load staticfiles %}


<!-- 网站主语言 -->
<html lang="zh-cn">
<!--html语法中。所有内容是被标签包裹的-->
<!--标签和标签中的属性可以对内容进行排印、解释说明等作用-->
<!--\<head\>\</head\>标签内包含网页的元数据，不会再页面内显示出来-->
<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 预留网站标题的位置 -->
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- 引入monikai.css -->
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">

    <!-- 第三方矢量图标-->
    <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.14.0/css/all.min.css"
    >
</head>

<!--\<body\>\</body\>标签内书网页显示的内容-->
<body>
<!-- 引入导航栏 -->
{% include 'header.html' %}
<!-- 预留具体页面的位置 -->
<!--\{\% block content %}\{\% endblock content %}-->
<!-- 新增两个 div 容器 -->
<div id="wrapper">
    {% block content %}{% endblock content %}
    <div id="push"></div>
</div>
<!-- 引入注脚 -->
{% include 'footer.html' %}
<!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里引入 -->
<script src="{% static 'jquery/jquery-3.3.1.js' %}"></script>

<!--
    popper.js 采用 cdn 远程引入，意思是你不需要把它下载到本地。
    在实际的开发中推荐静态文件尽量都使用 cdn 的形式。
-->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1-lts/dist/umd/popper.min.js"></script>

<!-- 引入bootstrap的js文件 -->
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<!-- 引入layer.js -->
<script src="{% static 'layer/layer.js' %}"></script>

<!-- 在jquery后面引入 -->
{% include 'back_to_top_func.html' %}
<!-- 解决评论区引入富文本的脚本而出现的错误   -->
{% block script %}{% endblock script %}

<!-- 增加样式 -->
<style>
    html, body {
        height: 100%;
        margin: 0;
    }

    /*#wrapper容器的底部有一个负边距，作用是给页脚容器让出位置。*/
    #wrapper {
        min-height: 100%;
        margin-bottom: -60px;
    }

    #footer,
        /*#push容器留出一段与页脚等高的空隙，避免正文内容与页脚重叠*/
    #push {
        height: 60px;
    }
</style>

</body>

</html>

templates/footer.html
{% load staticfiles %}
<!-- Footer -->
<div>
    <br><br><br>
</div>
<!-- 删除了 fixed-bottom 属性 -->
<!--<footer class="py-3 bg-dark">-->
<footer class="py-3 bg-dark" id="footer">
    <div class="container">
        <p class="m-0 text-center text-white">原始风格。能用就行</p>
    </div>
</footer>

templates/header.html
<!--标签内的 class 属性是 bootstrap 样式定义方法-->
<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <!-- 导航栏商标 -->
        <a class="navbar-brand" href="#">cat的博客</a>
        <!-- 导航入口 -->
        <div>
            <ul class="navbar-nav">
                <!-- 条目 -->
                <li class="nav-item">
                    <!-- 改写了这里的 href -->
                    <!-- href定义了链接跳转的地址。-->
                    <!-- \{\% url '...' \%\}是Django规定的模板解耦语法，-->
                    <!--用它可以根据我们在urls.py中设置的名字，反向解析到对应的url中去。-->
                    <!-- article:article_list 的解释-->
                    <!-- article 是在项目根目录的 urls.py 中定义的app的名称-->
                    <!-- article_list 是在 app 中的 urls.py 中定义的具体路由地址-->
                    <!--只要对应 url 名称不变， url 本身无论怎么变化， Django 都可以解析正确地址-->
                    <!--当然也可以直接在 href 中写入 url 的地址，-->
                    <!--但 url 变化，所有的相关链接都会失效-->
                    <a class="nav-link" href="{% url 'article:article_list' %}">文章</a>
                </li>
                <!-- Django的 if 模板语句 -->
                <!-- is_authenticated是models.User类的属性，用于判断用户是否已通过身份验证。-->
                {% if user.is_authenticated %}
                <!-- 如果用户已经登录，则显示用户名下拉框 -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle"
                       href="#"
                       id="navbarDropdown"
                       role="button"
                       data-toggle="dropdown"
                       aria-haspopup="true"
                       aria-expanded="false">

                        {% if unread_count %}
                        <svg viewBox="0 0 8 8"
                             width="8px"
                             height="8px">
                            <circle cx="4"
                                    cy="4"
                                    r="4"
                                    fill="#ff6b6b"
                            ></circle>
                        </svg>
                        {% endif %}
                        {{ user.username }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'notice:list' %}">通知
                        {% if unread_count %}
                        <span class="badge badge-danger">{{ unread_count }}</span>
                        {% endif %}
                        </a>
                        <a class="dropdown-item" href="#" onclick="user_delete()">删除用户</a>
                        <a class="dropdown-item" href='{% url "userprofile:edit" user.id %}'>个人信息</a>
                        <a class="dropdown-item" href="{% url 'article:article_create' %}">写文章</a>
                        <a class="dropdown-item" href='{% url "userprofile:logout" %}'>退出登录</a>
                    </div>
                </li>
                <!-- 如果用户未登录，则显示 “登录” -->
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'userprofile:login' %}">登录</a>
                </li>
                <!-- if 语句在这里结束 -->
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<!--因为删除用户要求用户必须登录，因此就把它的入口放在登陆后才显示的下拉框中，这样页面可以更加简洁。-->
<!--当然这种方式并不是最佳的选择，通常的做法是把删除功能放在独立的用户资料页面中。-->
<!--与删除文章类似，-->
<!--点击删除用户链接后调用了user_delete()函数，-->
<!--函数包含了弹窗组件确认用户没有误操作；-->
<!--点击弹窗中的确认按钮后，提交删除的隐藏表单，执行视图。-->
<!--注意到user_delete()函数和表单是用if模板语句包裹起来的。-->
<!--因为用户未登录时页面对象中是没有user.id属性的，-->
<!--但是函数中却又包含了user.id，Django在解析模板时就会报错。-->
<!--if语句确保了只有在用户登录时才对这段JavaScript代码进行解析，-->
<!--回避了这个问题。-->

<!--删除用户的函数-->
{% if user.is_authenticated %}
<form
        style="display:none;"
        id="user_delete"
        action="{% url 'userprofile:delete' user.id %}"
        method="POST"
>
    {% csrf_token %}
    <button type="submit">发送</button>
</form>
<script>
    function user_delete() {
        // 调用layer弹窗组件
        layer.open({
            title: "确认删除",
            content: "确认删除用户资料吗？",
            yes: function (index, layero) {
                $('form#user_delete button').click();
                layer.close(index);
            },
        })
    }
</script>
{% endif %}